

source("func.r")
load("UNC232.RData")

# provided file "Pam50_subpopulation_specific_gene_quantile.csv" is generated by 
# out = getSigma.generic(exprs(UNC232), pData(UNC232)); colnames(out)[6:ncol(out)] = c("ER_neg", "ER_pos", "nonTN", "TN")
# write.csv(out, "Pam50_subpopulation_specific_gene_quantile.csv") 

# Pam50 gene signature
Pam50 = signature.pam50()

save(list = ls(), file = "ssBCsubtyping.Rdata")

